
text { ttf "timrom.ttf", // Font
    "Authors: ", // Text
    4.5,
    0
    texture{ Polished_Chrome
        normal { bumps 0.5 scale 0.005}
        finish{specular 1 reflection 0.55}
    }
    scale 0.4
    translate<-2,0.6,clock+15*Fadein-5*Fadeout>
}

text { ttf "timrom.ttf", // Font
    "Arne Beer", // Text
    4.5,
    0
    texture{ Polished_Chrome
        normal { bumps 0.5 scale 0.005}
        finish{specular 1 reflection 0.55}
    }
    scale 0.4
    translate<-0.9,0,clock+15*Fadein-5*Fadeout>
}

text { ttf "timrom.ttf", // Font
    "Rafael Epplee", // Text
    4.5,
    0
    texture{ Polished_Chrome
        normal { bumps 0.5 scale 0.005}
        finish{specular 1 reflection 0.55}
    }
    scale 0.4
    translate<-1.2,-0.6,clock+15*Fadein-5*Fadeout>
}

text { ttf "timrom.ttf", // Font
    "Sven-Hendrik Haase", // Text
    4.5,
    0
    texture{ Polished_Chrome
        normal { bumps 0.5 scale 0.005}
        finish{specular 1 reflection 0.55}
    }
    scale 0.4
    translate<-1.7,-1.2,clock+15*Fadein-5*Fadeout>
}

